### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/layer-hadoop-base#2]
This is quite possibly a bug in charms.reactive and not hadoop-base.

```
unit-plugin-0[9862]: 2016-01-09 00:16:36 INFO unit.plugin/0.juju-log server.go:268 conversations:
unit-plugin-0[9862]: 2016-01-09 00:16:36 INFO unit.plugin/0.juju-log server.go:268   reactive.conversations.yarn.global:
unit-plugin-0[9862]: 2016-01-09 00:16:36 INFO unit.plugin/0.juju-log server.go:268     relation_ids:
unit-plugin-0[9862]: 2016-01-09 00:16:36 INFO unit.plugin/0.juju-log server.go:268     - client:5
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268     relation_name: yarn
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268     scope: global
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268     units:
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268     - resourcemanager/0
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268 relation_data:
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268   yarn:4:
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268     resourcemanager/0:
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268       hosts-map: '{"172.31.42.235": "resourcemanager-0"}'
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268       hs_http: '19888'
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268       hs_ipc: '10020'
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268       port: '8032'
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268       private-address: 172.31.42.235
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268       resourcemanagers: '["resourcemanager-0"]'
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268       spec: '{"java": "1.8.0", "arch": "x86_64", "vendor": "apache", "hadoop": "2.7.1"}'
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268       yarn-ready: 'True'
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.juju-log server.go:268 relation_name: yarn
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40 Traceback (most recent call last):
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40   File "/var/lib/juju/agents/unit-plugin-0/charm/hooks/update-status", line 18, in <module>
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40     main()
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/__init__.py", line 67, in main
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40     bus.dispatch()
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 405, in dispatch
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40     _invoke(other_handlers)
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 388, in _invoke
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40     handler.invoke()
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 269, in invoke
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40     self._action(*args)
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40   File "/var/lib/juju/agents/unit-plugin-0/charm/reactive/hadoop.py", line 101, in configure_yarn
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40     yarn.configure_yarn_base(resourcemanager.resourcemanagers()[0], resourcemanager.port(),
unit-plugin-0[9862]: 2016-01-09 00:16:37 INFO unit.plugin/0.update-status logger.go:40 IndexError: list index out of range
unit-plugin-0[9862]: 2016-01-09 00:16:37 ERROR juju.worker.uniter.operation runhook.go:107 hook "update-status" failed: exit status 1
```

**Comment by kwmonroe** [comment]
resolved with:

https://github.com/juju-solutions/charms.reactive/commit/e30b43923bc1c0b449ef55a10e528aa76beabd55
